version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mytestsam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q6lahu30q1v8"
s3_prefix = "mytestsam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"trackntracesam\""
image_repositories = []
